package au.edu.unsw.soacourse.crv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-13T11:27:23.764+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CRVCheckService", 
                  wsdlLocation = "file:/Users/williamfeng/Study/COMP9322/Assignment2/CRVCheck/src/main/resources/wsdl/CRVCheckService.wsdl",
                  targetNamespace = "http://crv.soacourse.unsw.edu.au") 
public class CRVCheckService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://crv.soacourse.unsw.edu.au", "CRVCheckService");
    public final static QName CRVCheckServiceSOAP = new QName("http://crv.soacourse.unsw.edu.au", "CRVCheckServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/williamfeng/Study/COMP9322/Assignment2/CRVCheck/src/main/resources/wsdl/CRVCheckService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRVCheckService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/williamfeng/Study/COMP9322/Assignment2/CRVCheck/src/main/resources/wsdl/CRVCheckService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRVCheckService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRVCheckService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRVCheckService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVCheckService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVCheckService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVCheckService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CRVCheckService
     */
    @WebEndpoint(name = "CRVCheckServiceSOAP")
    public CRVCheckService getCRVCheckServiceSOAP() {
        return super.getPort(CRVCheckServiceSOAP, CRVCheckService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRVCheckService
     */
    @WebEndpoint(name = "CRVCheckServiceSOAP")
    public CRVCheckService getCRVCheckServiceSOAP(WebServiceFeature... features) {
        return super.getPort(CRVCheckServiceSOAP, CRVCheckService.class, features);
    }

}
