package au.edu.unsw.soacourse.autocheck;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-13T00:07:31.908+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "AutoCheckServiceProcess", 
                  wsdlLocation = "file:/Users/williamfeng/Study/COMP9322/Assignment2/ORSClient/src/main/resources/wsdl/AutoCheckServiceProcess.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/autocheck") 
public class AutoCheckServiceProcess extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/autocheck", "AutoCheckServiceProcess");
    public final static QName AutoCheckPort = new QName("http://soacourse.unsw.edu.au/autocheck", "AutoCheckPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/williamfeng/Study/COMP9322/Assignment2/ORSClient/src/main/resources/wsdl/AutoCheckServiceProcess.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutoCheckServiceProcess.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/williamfeng/Study/COMP9322/Assignment2/ORSClient/src/main/resources/wsdl/AutoCheckServiceProcess.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutoCheckServiceProcess(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutoCheckServiceProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoCheckServiceProcess() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoCheckServiceProcess(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoCheckServiceProcess(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutoCheckServiceProcess(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AutoCheckServiceProcessPortType
     */
    @WebEndpoint(name = "AutoCheckPort")
    public AutoCheckServiceProcessPortType getAutoCheckPort() {
        return super.getPort(AutoCheckPort, AutoCheckServiceProcessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoCheckServiceProcessPortType
     */
    @WebEndpoint(name = "AutoCheckPort")
    public AutoCheckServiceProcessPortType getAutoCheckPort(WebServiceFeature... features) {
        return super.getPort(AutoCheckPort, AutoCheckServiceProcessPortType.class, features);
    }

}
