package au.edu.unsw.soacourse.pdv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-10T18:48:26.653+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "PDVCheckService", 
                  wsdlLocation = "file:/Users/williamfeng/Study/COMP9322/Assignment2/PDVCheck/src/main/resources/wsdl/PDVCheckService.wsdl",
                  targetNamespace = "http://pdv.soacourse.unsw.edu.au") 
public class PDVCheckService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pdv.soacourse.unsw.edu.au", "PDVCheckService");
    public final static QName PDVCheckServiceSOAP = new QName("http://pdv.soacourse.unsw.edu.au", "PDVCheckServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/williamfeng/Study/COMP9322/Assignment2/PDVCheck/src/main/resources/wsdl/PDVCheckService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PDVCheckService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/williamfeng/Study/COMP9322/Assignment2/PDVCheck/src/main/resources/wsdl/PDVCheckService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PDVCheckService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PDVCheckService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDVCheckService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVCheckService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVCheckService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVCheckService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PDVCheckService
     */
    @WebEndpoint(name = "PDVCheckServiceSOAP")
    public PDVCheckService getPDVCheckServiceSOAP() {
        return super.getPort(PDVCheckServiceSOAP, PDVCheckService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDVCheckService
     */
    @WebEndpoint(name = "PDVCheckServiceSOAP")
    public PDVCheckService getPDVCheckServiceSOAP(WebServiceFeature... features) {
        return super.getPort(PDVCheckServiceSOAP, PDVCheckService.class, features);
    }

}
